directories:
  stored_csv_xlsx_directory: data/csv_xlsx
  sqldb_directory: data/sqldb.db
  uploaded_files_sqldb_directory: data/uploaded_files_sqldb.db
  stored_csv_xlsx_sqldb_directory: data/csv_xlsx_sqldb.db


llm_config:
  agent_llm_system_role: |
    Given the following user question, corresponding SQL query, and SQL result, answer the user question.
    Question: {question}
    SQL Query: {query}
    SQL Result: {result}
    Answer: 
  rag_llm_system_role: |
    You will receive the user's question along with the search results of that question over a database. Give the user the proper answer.
  sql_generation_prompt: |
    You are a SQL expert.
    Write only a valid SQLite SQL query as output.
    Do not include markdown, triple backticks, or explanations.

    Tables:
    {table_info}

    Question:
    {input}

    Return at most {top_k} rows if applicable.

    SQL:
  engine: "gemini-2.5-flash"
  temperature: 0.0